language: python
fast_finish: true

python:
  - 3.5
  - 3.7

os:
  - linux

dist: trusty
group: edge
  
env: FC=gfortran-6

notifications:
  email: false

git:
  depth: 3

# gfortran >= 6 required
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

before_install:
    - pip -q install coveralls
    # temp for pip < 9.1
    - pip -q install numpy

install: pip -q install -e .

script: 
  - coverage run tests/test.py -v

after_success: coveralls

