language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
  - 3.7

os:
  - linux

env: FC=gfortran-6

# gfortran >= 6 required
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

install: 
  - pip install -e .[tests]

  - cd bin
  - cmake ..
  - cmake --build .

script:
  - ctest -V

  - cd ..
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

