language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
  - 3.7

os:
  - linux

env: FC=gfortran-6

before_install:
# FIXME: until Travis Xenial gets whitelist updated
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -yq gfortran-6

install:
  - pip install -e .[tests]

  - cd bin
  - cmake ..
  - cmake --build .

script:
  - ctest -V

  - cd ..
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

