language: python
fast_finish: true

python:
  - 3.5
  - 3.6

os:
  - linux
  
group: travis_latest

env: FC=gfortran-6


git:
  depth: 3

# gfortran >= 6 required
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

before_install:
  # temp for pip < 9.1
  - pip -q install numpy

install: 
  - pip -q install -e .[tests]
  - cd bin
  - cmake ..
  - make

script:
  - make test

after_success: 
  -  coverage run tests/test_all.py
  - coveralls

