image:
- Visual Studio 2017
#- ubuntu1804 appveyor broken import lzma, go to azure

stack: python 3.7

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- ps: if ($isWindows) {echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg}

install:
- pip install -e .[tests]

test_script: pytest -r a -v

artifacts:
  - path: lowtran7.cp37-win_amd64.pyd
