name: ci_unix

on:
  push:
    paths:
      - "**.build"
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - "*.py"
      - ".github/workflows/ci_unix.yml"
  pull_request:
  release:


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: |
        sudo apt update
        sudo apt install -yq --no-install-recommends gfortran

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest

    - run: ctest -S setup.cmake -V
      env:
        FC: gfortran-9


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install .[tests]
    - run: pytest

    - run: ctest -S setup.cmake -V
      env:
        FC: gfortran-9
