name: ci_unix

on:
  push:
    paths:
      - "**.txt"
      - "**.cmake"
      - "**.f90"
      - "**.py"
      - ".github/workflows/ci_unix.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

  # f2py is seriously broken for finding fortran compilers
    - name: prereqs for f2py
      run: |
        sudo apt -yq update
        sudo apt -yq install --no-install-recommends gfortran

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy .

    - run: pytest

    - run: ctest -S setup.cmake -V


  macos:
    needs: linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]
      env:
        FC: gfortran-9

    - run: pytest

    - run: ctest -S setup.cmake -V
      env:
        FC: gfortran-9
